Generate password
PlatziMaster/challenge-python-02 pull request #16
Opened 2020-03-30 22:57 UTC by ealexisaraujo

Generate password

2020-04-05 17:18 UTC, hyfi06 requested changes
Some comments

2020-04-05 17:18 UTC, hyfi06 commented on src/main.py
> +def generate_password(length=21):
Para que usas `length=21`?

2020-04-05 17:18 UTC, hyfi06 commented on src/main.py
> +    # ascii_upper = string.ascii_lowercase.upper()
Trata de limpiar tu código.

2020-04-05 17:18 UTC, hyfi06 commented on src/main.py
> +    s = "abcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()?"
Usa nombres de variables más significativas a su función

2020-04-05 17:18 UTC, hyfi06 commented on src/main.py
> +    p = "".join(random.sample(s, passlen))
Esto falla aproximadamente el 10.7% de las veces. No tienes el control de que incluya cada tipo de caracteres.

2020-04-12 00:00 UTC, ealexisaraujo commented
Gracias por toda tu ayuda @hyfi06 . @ealexisaraujo

2020-04-12 00:10 UTC, ealexisaraujo commented
GitHub contribution graph colors: `#C6E48B` `#7AC96F` `#249A3C` `#196127`

2020-04-12 00:17 UTC, ealexisaraujo commented
Listado de problemas
<details>
<summary>Click here to see terminal history + debug info</summary>
<pre>
488 cd /opt/LLL/controller/laser/
489 vi LLLSDLaserControl.c
490 make
491 make install
492 ./sanity_check
493 ./configure -o test.cfg
494 vi test.cfg
495 vi ~/last_will_and_testament.txt
496 cat /proc/meminfo
497 ps -a -x -u
498 kill -9 2207
499 kill 2208
500 ps -a -x -u
501 touch /opt/LLL/run/ok
502 LLLSDLaserControl -ok1

2022-08-29 22:48 UTC, closed without merging

2022-08-29 23:04 UTC, hyfi06 commented
:eyes:

2022-08-29 23:40 UTC, ealexisaraujo commented
> :eyes: 

Estaba cerrando todos mis pull request para dejar limpio mi lista de prs jajaja